name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    name: "ci"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Boostrap
        run: npx lerna bootstrap --force-local

      - name: Check changed
        id: check-changed
        run: echo "::set-output name=CHANGED_PACKAGES::$( npx lerna ls --since origin/master )"

      - name: echo
        run: echo "changed packages are ${{ steps.check-changed.outputs.CHANGED_PACKAGES }}"
