name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    name: "ci"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Boostrap
        run: npx lerna bootstrap --since master

      - name: Test
        run: npx lerna run test --since master
